#!/usr/bin/env bash
# shellcheck disable=SC2154
# Configure Nginx for copy web 01 to web 02

sudo apt-get -y update
sudo apt-get -y install nginx

sudo ufw allow 'Nginx HTTP'

# make dirctory then change mode for all permission
sudo mkdir -p /var/www/html
sudo chmod -R 755 /var/www

echo "Hello World!" > /var/www/html/index.html

echo "Ceci n'est pas une page" > /var/www/html/custom_404.html

echo "server {
   server_name _;
   tadd_header X-Served-By $hostname;
   rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;

   listen 80 default_server;
   listen [::]:80 default_server;
   
   root /var/www/html;
   index index.html;
   location /redirect_me {
      return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
   }
   error_page 404 /custom_404.html;
   location = /custom_404.html{
      internal;
   }
}" > default

sudo mv -f default /etc/nginx/sites-available/default

sudo service nginx restart
