#!/usr/bin/env bash
# this script for load balancer server lb-01

sudo apt-get -y update
sudo apt-get -y install haproxy

server_code=\
"
frontend http80-frontend
	bind *:80
	mode http
	default_backend allServers-backend

backend allServers-backend
	balance roundrobin
	server 509946-web-01 54.175.199.26:80 check
	server 509946-web-02 107.23.117.21:80 check
"

echo "$server_code" | sudo tee -a /etc/haproxy/haproxy.cfg

echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

sudo service haproxy restart
